# -*- coding: utf-8 -*-
"""Модуль рекомендаций.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jl04Miifht8i5wrPiF0mR2_ueSFVHnzM

Импорт библиотек
"""

import random
import pandas as pd
import numpy as np
from collections import defaultdict
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.model_selection import train_test_split

"""1. Загрузка и подготовка данных"""

# Генерация авторов и их категорий
authors = {
    'Леонардо да Винчи': ['портрет', 'ренессанс', 'религиозная'],
    'Винсент Ван Гог': ['пейзаж', 'постимпрессионизм', 'натюрморт', 'портрет'],
    'Клод Моне': ['пейзаж', 'импрессионизм', 'сад'],
    'Рембрандт': ['портрет', 'барокко', 'религиозная'],
    'Пабло Пикассо': ['кубизм', 'абстракция', 'портрет'],
    'Сальвадор Дали': ['сюрреализм', 'пейзаж', 'абстракция'],
    'Иван Айвазовский': ['марина', 'пейзаж', 'романтизм'],
    'Иван Шишкин': ['пейзаж', 'реализм', 'лес'],
    'Микеланджело': ['скульптура', 'ренессанс', 'религиозная'],
    'Казимир Малевич': ['супрематизм', 'абстракция']
}

# Генерация работ на основе категорий авторов
artwork_data = []
artwork_id = 1
for author, cats in authors.items():
    num_artworks = random.randint(1, 3)
    for _ in range(num_artworks):
        chosen_cats = random.sample(cats, k=random.randint(1, 2))
        categories_str = ','.join(chosen_cats)
        artwork_data.append({
            'artwork_id': artwork_id,
            'author': author,
            'categories': categories_str
        })
        artwork_id += 1

artworks = pd.DataFrame(artwork_data)

# Генерация пользователей и их предпочтений
num_users = 10
user_preferences = {}
for user_id in range(1, num_users + 1):
    preferred_cats = random.sample([
        'портрет', 'пейзаж', 'натюрморт', 'импрессионизм',
        'постимпрессионизм', 'ренессанс', 'барокко', 'абстракция',
        'сюрреализм', 'марина', 'реализм', 'кубизм', 'религиозная'
    ], k=random.randint(2, 4))

    preferred_authors = random.sample(list(authors.keys()), k=random.randint(1, 3))

    user_preferences[user_id] = {
        'preferred_cats': preferred_cats,
        'preferred_authors': preferred_authors
    }

# Генерация рейтинга, понравившихся работ
interactions_list = []

for user_id in range(1, num_users + 1):
    pref = user_preferences[user_id]
    viewed_artworks = random.sample(list(artworks['artwork_id']),
                                    k=random.randint(2, min(8, len(artworks))))

    for art_id in viewed_artworks:
        artwork_row = artworks[artworks['artwork_id'] == art_id].iloc[0]
        author = artwork_row['author']
        categories = artwork_row['categories'].split(',')

        like = 0
        if author in pref['preferred_authors']:
            like = 1 if random.random() < 0.8 else 0
        elif any(cat in pref['preferred_cats'] for cat in categories):
            like = 1 if random.random() < 0.6 else 0
        else:
            like = 1 if random.random() < 0.1 else 0

        view = 1

        interactions_list.append({
            'user_id': user_id,
            'artwork_id': art_id,
            'like': like,
            'view': view
        })

interactions = pd.DataFrame(interactions_list)
interactions['rating'] = interactions['like'] * 1.0 + interactions['view'] * 0.2
interactions = interactions.sort_values(['user_id', 'artwork_id']).reset_index(drop=True)

"""2. Контентная фильтрация. Признаки: автор и категория"""

# Текстовое представление для каждого произведения
artworks['features'] = artworks['author'] + ' ' + artworks['categories']
tfidf = TfidfVectorizer(token_pattern=r'(?u)\b\w+\b')
feature_matrix = tfidf.fit_transform(artworks['features'])
content_sim = cosine_similarity(feature_matrix)

def get_content_recommendations(artwork_id, top_n=3):
    # Рекомендации на основе сходства с заданным произведением
    sim_scores = list(enumerate(content_sim[artwork_id-1]))
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
    sim_scores = sim_scores[1:top_n+1]
    return [artworks.iloc[i[0]]['artwork_id'] for i in sim_scores]

"""3. Коллаборативная фильтрация (SVD через матричную факторизацию)"""

class SimpleSVD:
    """Реализация SVD для рекомендательных систем через стохастический градиентный спуск"""
    
    def __init__(self, n_factors=10, lr=0.005, reg=0.02, n_epochs=20):
        self.n_factors = n_factors
        self.lr = lr
        self.reg = reg
        self.n_epochs = n_epochs
        self.user_factors = None
        self.item_factors = None
        self.user_bias = None
        self.item_bias = None
        self.global_mean = None
    
    def fit(self, user_ids, item_ids, ratings):
        self.global_mean = np.mean(ratings)
        # Используем максимальные ID для определения размера массивов
        max_user_id = int(np.max(user_ids))
        max_item_id = int(np.max(item_ids))
        
        # Инициализация факторов и смещений (+1 для 1-based индексации)
        np.random.seed(42)
        self.user_factors = np.random.normal(0, 0.1, (max_user_id + 1, self.n_factors))
        self.item_factors = np.random.normal(0, 0.1, (max_item_id + 1, self.n_factors))
        self.user_bias = np.zeros(max_user_id + 1)
        self.item_bias = np.zeros(max_item_id + 1)
        
        # SGD обучение
        for epoch in range(self.n_epochs):
            indices = np.arange(len(ratings))
            np.random.shuffle(indices)
            
            for idx in indices:
                u = user_ids[idx]
                i = item_ids[idx]
                r = ratings[idx]
                
                # Предсказание
                pred = self.global_mean + self.user_bias[u] + self.item_bias[i] + \
                       np.dot(self.user_factors[u], self.item_factors[i])
                
                # Ошибка
                err = r - pred
                
                # Обновление параметров
                self.user_bias[u] += self.lr * (err - self.reg * self.user_bias[u])
                self.item_bias[i] += self.lr * (err - self.reg * self.item_bias[i])
                
                old_uf = self.user_factors[u].copy()
                self.user_factors[u] += self.lr * (err * self.item_factors[i] - self.reg * self.user_factors[u])
                self.item_factors[i] += self.lr * (err * old_uf - self.reg * self.item_factors[i])
    
    def predict(self, user_id, item_id):
        pred = self.global_mean + self.user_bias[user_id] + self.item_bias[item_id] + \
               np.dot(self.user_factors[user_id], self.item_factors[item_id])
        return max(0, min(pred, 1.2))  # Ограничение диапазона


# Подготовка данных для SVD
all_user_ids = interactions['user_id'].values.astype(int)
all_item_ids = interactions['artwork_id'].values.astype(int)
all_ratings = interactions['rating'].values

# Разделение на train/test
user_idx, test_idx = train_test_split(
    np.arange(len(interactions)), test_size=0.25, random_state=42
)

train_users = all_user_ids[user_idx]
train_items = all_item_ids[user_idx]
train_ratings = all_ratings[user_idx]

test_users = all_user_ids[test_idx]
test_items = all_item_ids[test_idx]
test_ratings = all_ratings[test_idx]

# Обучение SVD
svd = SimpleSVD(n_factors=10, lr=0.005, reg=0.02, n_epochs=20)
svd.fit(train_users, train_items, train_ratings)


def get_collab_recommendations(user_id, all_artwork_ids, top_n=3):
    # Рекомендации на основе предсказанных рейтингов SVD
    predictions = []
    for aid in all_artwork_ids:
        pred = svd.predict(user_id, int(aid))
        predictions.append((aid, pred))
    predictions.sort(key=lambda x: x[1], reverse=True)
    return [p[0] for p in predictions[:top_n]]

"""4. Гибридная система"""

def hybrid_recommendations(user_id, interactions_df, artworks_df, alpha=0.6, top_n=3):
    """
    alpha – вес коллаборативной составляющей,
    1-alpha – вес контентной составляющей.
    """
    # Все произведения, с которыми пользователь ещё не взаимодействовал
    seen = interactions_df[interactions_df['user_id']==user_id]['artwork_id'].tolist()
    candidates = [aid for aid in artworks_df['artwork_id'] if aid not in seen]
    if not candidates:
        return []

    # Коллаборативные предсказания
    collab_scores = {}
    for aid in candidates:
        pred = svd.predict(user_id, int(aid))
        collab_scores[aid] = pred

    # Контентные предсказания: усреднение по всем лайкнутым пользователем произведениям
    liked = interactions_df[(interactions_df['user_id']==user_id) & (interactions_df['like']==1)]['artwork_id'].tolist()
    content_scores = {}
    for aid in candidates:
        scores = []
        for liked_id in liked:
            scores.append(content_sim[liked_id-1][aid-1])
        content_scores[aid] = np.mean(scores) if scores else 0

    # Нормализация оценок к диапазону [0,1]
    max_collab = max(collab_scores.values()) if collab_scores else 1
    max_content = max(content_scores.values()) if content_scores else 1
    hybrid = {}
    for aid in candidates:
        collab_norm = collab_scores[aid] / max_collab if max_collab > 0 else 0
        content_norm = content_scores[aid] / max_content if max_content > 0 else 0
        hybrid[aid] = alpha * collab_norm + (1-alpha) * content_norm

    # Сортировка и возврат top_n
    sorted_items = sorted(hybrid.items(), key=lambda x: x[1], reverse=True)
    return [aid for aid, _ in sorted_items[:top_n]]

"""5. Пример использования"""

user = 1
user_history = interactions[interactions['user_id'] == user]
liked = user_history[user_history['like'] == 1]['artwork_id'].tolist()
viewed_only = user_history[(user_history['view'] == 1) & (user_history['like'] == 0)]['artwork_id'].tolist()
print(f"\n======= История пользователя {user} =======")
if liked:
    print("Произведения, которые пользователю понравились (лайк):")
    for aid in liked:
        art = artworks[artworks['artwork_id'] == aid].iloc[0]
        print(f"  - ID {aid}: {art['author']} - {art['categories']}")
else:
    print("Нет понравившихся произведений.")
if viewed_only:
    print("\nПросмотренные, но не отмеченные лайком:")
    for aid in viewed_only:
        art = artworks[artworks['artwork_id'] == aid].iloc[0]
        print(f"  - ID {aid}: {art['author']} - {art['categories']}")
else:
    print("\nНет просмотров без лайка.")
print("\n======= Рекомендации для пользователя =======")
recs = hybrid_recommendations(user, interactions, artworks, alpha=0.6, top_n=3)
for aid in recs:
    art = artworks[artworks['artwork_id'] == aid].iloc[0]
    print(f" - Произведение {aid}: {art['author']} - {art['categories']}")

"""6. Оценка качества рекомендаций"""

# Функции метрик
def precision_recall_at_k(predictions, k=3, threshold=1.0):
    """Для каждого пользователя считаем Precision@k и Recall@k.
       Релевантным считается произведение с истинным рейтингом >= threshold (т.е. like=1)"""
    user_est_true = defaultdict(list)
    for uid, iid, true_r, est, _ in predictions:
        user_est_true[uid].append((est, true_r))

    precisions = []
    recalls = []

    for uid, user_ratings in user_est_true.items():
        user_ratings.sort(key=lambda x: x[0], reverse=True)
        top_k = user_ratings[:k]

        relevant = sum(1 for (_, true_r) in user_ratings if true_r >= threshold)
        retrieved = sum(1 for (_, true_r) in top_k if true_r >= threshold)

        precisions.append(retrieved / k)
        recalls.append(retrieved / relevant if relevant > 0 else 0)

    return np.mean(precisions), np.mean(recalls)

def coverage(predictions, all_item_ids, k=3):
    # Доля уникальных произведений, попавших в top-k рекомендаций
    recommended_items = set()
    user_predictions = defaultdict(list)
    for uid, iid, _, est, _ in predictions:
        user_predictions[uid].append((iid, est))

    for uid, items in user_predictions.items():
        items.sort(key=lambda x: x[1], reverse=True)
        top_k_items = [iid for iid, _ in items[:k]]
        recommended_items.update(top_k_items)

    return len(recommended_items) / len(all_item_ids)

test_predictions = []
for u, i, r in zip(test_users, test_items, test_ratings):
    pred = svd.predict(u, i)
    test_predictions.append((u, i, r, pred, None))

# Precision@3, Recall@3
k = 3
precision, recall = precision_recall_at_k(test_predictions, k=k, threshold=1.0)
print(f"Precision@{k} = {precision:.3f}")
print(f"Recall@{k} = {recall:.3f}")

# Coverage@3
all_artwork_ids = artworks['artwork_id'].tolist()
cov = coverage(test_predictions, all_artwork_ids, k=k)
print(f"Coverage = {cov:.3f}")